##########################
#          IRMC          #
#  Plugin Configuration  #
##########################

account:
    #the name the bot will use
    nick: 'Professor`Oak'
    #the channel the bot will join on startup.
    channel: '#branicyeti'