############################################################
# +------------------------------------------------------+ #
# |                         IRMC                         | #
# +------------------------------------------------------+ #
############################################################

# This is the default config file for IRMC (Internet Relay Minecraft Chat). When editting this file, it is of utmost importance that you follow YAML standards.
# Essentials have an excellent tutorial on YAML here: http://wiki.ess3.net/wiki/YAML_Tutorial
# Essentials also have an excellent YAML syntax checker here: http://wiki.ess3.net/yaml/
# The syntax checker will NOT fix your YAML file for you. It will simply tell you what is wrong with your file that you need to fix.

############################################################
# +------------------------------------------------------+ #
# |              Minecraft Server Settings               | #
# +------------------------------------------------------+ #
############################################################

# These settings are for the configuration of the plugin on the server side. These settings shouldn't interfere with the IRC side at all.
bukkit:


############################################################
# +------------------------------------------------------+ #
# |                  IRC Bot Settings                    | #
# +------------------------------------------------------+ #
############################################################

# These settings are for the configuration of the IRC Bot. These settings shouldn't interfere with the Bukkit server at all.
irc:
  debug: true
  verbose: true
  auto-change-nick: true
  auto-rejoin-channel: true
  auto-reconnect-server: true
  auto-split-message: true
  identity:
    nickname:
    ident:
    password:
  server:
    address: irc.esper.net
    port: 6697
    password: ''
    use-ssl: true
    verify-ssl: true
  channels:
  - #channel
  - #channel